name: Build
on: [push, workflow_dispatch]

env:
  IMAGE: ghcr.io/dellelce/mkitpy

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t $IMAGE .
      - name: Add tag & push
        run: docker push $IMAGE
